-- [1m[38;5;214mFailure[39m (Line 3): new('Data') works with  Simulation_1.csv[22m --------------------
`Data <- new("Data", file.path(path, fl))` threw an error.
Message: subscript out of bounds
Class:   simpleError/error/condition
[1mBacktrace:[22m
[90m  1. [39mtestthat::expect_error(...)
[90m  6. [39mmethods::new("Data", file.path(path, fl))
[90m  8. [39mMSEtool:::initialize(value, ...)
[90m  9. [39mMSEtool:::.local(.Object, ...)
[90m 10. [39mMSEtool::XL2Data(stock, ...) [90mR/Class_definitions.R:206:4[39m

-- [1m[38;5;214mFailure[39m (Line 4): new('Data') works with  Simulation_1.csv[22m --------------------
`summary(Data, wait = FALSE)` threw an error.
Message: error in evaluating the argument 'object' in selecting a method for function 'summary': object 'Data' not found
Class:   simpleError/error/condition
[1mBacktrace:[22m
[90m 1. [39mtestthat::expect_error(summary(Data, wait = FALSE), NA)
[90m 7. [39mbase::.handleSimpleError(...)
[90m 8. [39mbase:::h(simpleError(msg, call))

